[0.269s] Invoking command in '/home/ryo/ros2_ws/build/person_msgs': CMAKE_PREFIX_PATH=/home/ryo/ros2_ws/install/mypkg:/opt/ros/humble /usr/bin/cmake --build /home/ryo/ros2_ws/build/person_msgs -- -j8 -l8
[0.294s] -- Found ament_cmake: 1.3.2 (/opt/ros/humble/share/ament_cmake/cmake)
[0.488s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.492s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.501s] -- Found rosidl_adapter: 3.1.3 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.553s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.799s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.799s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[0.799s]   person_msgs --arguments-file
[0.800s]   /home/ryo/ros2_ws/build/person_msgs/rosidl_adapter__arguments__person_msgs.json
[0.800s]   --output-dir /home/ryo/ros2_ws/build/person_msgs/rosidl_adapter/person_msgs
[0.800s]   --output-file
[0.800s]   /home/ryo/ros2_ws/build/person_msgs/rosidl_adapter/person_msgs.idls)
[0.801s]   returned error code 1:
[0.801s] 
[0.801s]   Error processing 'unit8 age' of 'person_msgs/Person': ''unit8' is an
[0.801s]   invalid message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$''
[0.801s] 
[0.801s]   Traceback (most recent call last):
[0.801s] 
[0.802s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.802s]       return _run_code(code, main_globals, None,
[0.802s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.802s]       exec(code, run_globals)
[0.802s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.802s]       sys.exit(main())
[0.802s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.802s]       abs_idl_file = convert_to_idl(
[0.802s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.802s]       return convert_msg_to_idl(
[0.802s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.802s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.803s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
[0.803s]       Type(type_string, context_package_name=pkg_name),
[0.803s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
[0.803s]       super(Type, self).__init__(
[0.803s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.803s]       raise InvalidResourceName(
[0.803s] 
[0.804s]   rosidl_adapter.parser.InvalidResourceName: 'unit8' is an invalid message
[0.804s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.804s] 
[0.804s] Call Stack (most recent call first):
[0.804s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.805s]   CMakeLists.txt:11 (rosidl_generate_interfaces)
[0.805s] 
[0.806s] [0m
[0.806s] -- Configuring incomplete, errors occurred!
[0.807s] See also "/home/ryo/ros2_ws/build/person_msgs/CMakeFiles/CMakeOutput.log".
[0.807s] gmake: *** [Makefile:226: cmake_check_build_system] ã‚¨ãƒ©ãƒ¼ 1
[0.810s] Invoked command in '/home/ryo/ros2_ws/build/person_msgs' returned '2': CMAKE_PREFIX_PATH=/home/ryo/ros2_ws/install/mypkg:/opt/ros/humble /usr/bin/cmake --build /home/ryo/ros2_ws/build/person_msgs -- -j8 -l8
